blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/williamzujkowski/dev-box/discussions
    about: Ask questions and discuss with the community
  - name: Security Issues
    url: https://github.com/williamzujkowski/dev-box/security/policy
    about: Report security vulnerabilities privately