# Default Sandbox Configuration

# Basic sandbox settings
sandbox_id: "default-sandbox"
workspace_path: "/tmp/sandbox-workspace"
auto_cleanup: true
snapshot_frequency: 300 # seconds
max_execution_time: 3600 # seconds

# Resource limits
resource_limits:
  memory_mb: 1024
  cpu_percent: 50
  disk_mb: 2048
  network:
    max_bandwidth_mbps: 10
    max_connections: 50

# Safety constraints
safety_constraints:
  # Snapshot settings
  max_snapshots: 10
  compress_snapshots: true
  incremental_snapshots: true
  auto_cleanup_hours: 168 # 1 week
  encrypt_snapshots: false
  encrypt_state: false

  # Content size limits
  max_content_size_mb: 10

  # Network constraints
  network:
    allow_external: false
    required: false

# Monitoring configuration
monitoring_config:
  collection_interval: 30 # seconds
  health_check_interval: 60 # seconds
  max_operation_history: 1000

  # Resource thresholds
  resource_thresholds:
    cpu_percent: 80
    memory_percent: 80
    disk_percent: 80
    memory_mb: 800
    disk_mb: 1600
    min_free_space_mb: 100

  # Critical thresholds
  critical_thresholds:
    cpu_percent: 95
    memory_percent: 95
    disk_percent: 95
    max_zombie_processes: 10
    max_total_processes: 1000

  # Warning thresholds
  warning_thresholds:
    cpu_percent: 70
    memory_percent: 70
    disk_percent: 70

  # Health check configuration
  enabled_health_checks:
    - resource_usage
    - filesystem
    - process_health
    - network
    - application

  # Recovery settings
  auto_recovery: true
