name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/dev-box-site/**"
      - ".github/workflows/build-docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/dev-box-site/**"
      - ".github/workflows/build-docs.yml"
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: docs/dev-box-site/package-lock.json

      - name: Install dependencies
        working-directory: docs/dev-box-site
        run: npm ci

      - name: Build documentation site
        working-directory: docs/dev-box-site
        run: npm run build

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-${{ matrix.node-version }}
          path: docs/dev-box-site/_site/
          retention-days: 7

      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports-${{ matrix.node-version }}
          path: docs/dev-box-site/.lighthouseci/
          retention-days: 7

  # Deployment removed - GitHub Pages not configured
  # Will add back when Pages is enabled for the repository

  # Validation removed - missing required doc pages
  # Will add back when documentation is complete
