name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/dev-box-site/**"
      - ".github/workflows/build-docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/dev-box-site/**"
      - ".github/workflows/build-docs.yml"
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: docs/dev-box-site/package-lock.json

      - name: Install dependencies
        working-directory: docs/dev-box-site
        run: npm ci

      - name: Lint documentation
        working-directory: docs/dev-box-site
        run: |
          npm run lint:markdown
          npm run lint:css

      - name: Build documentation site
        working-directory: docs/dev-box-site
        run: npm run build:ci

      - name: Check for broken links
        working-directory: docs/dev-box-site
        run: npm run test:links

      - name: Run Lighthouse CI
        working-directory: docs/dev-box-site
        run: |
          npm install -g @lhci/cli
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Test accessibility
        working-directory: docs/dev-box-site
        run: npm run test:a11y

      - name: Check bundle size
        working-directory: docs/dev-box-site
        run: npm run test:bundle-size

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-${{ matrix.node-version }}
          path: docs/dev-box-site/_site/
          retention-days: 7

      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports-${{ matrix.node-version }}
          path: docs/dev-box-site/.lighthouseci/
          retention-days: 7

  deploy-docs:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-docs
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: docs/dev-box-site/package-lock.json

      - name: Install dependencies
        working-directory: docs/dev-box-site
        run: npm ci

      - name: Build for production
        working-directory: docs/dev-box-site
        run: npm run build:production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dev-box-site/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  validate-quality:
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: docs/dev-box-site/package-lock.json

      - name: Install dependencies
        working-directory: docs/dev-box-site
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build-20
          path: docs/dev-box-site/_site/

      - name: Validate HTML
        working-directory: docs/dev-box-site
        run: npm run test:html-validate

      - name: Check SEO optimization
        working-directory: docs/dev-box-site
        run: npm run test:seo

      - name: Validate documentation completeness
        working-directory: docs/dev-box-site
        run: |
          # Check that all required sections exist
          test -f _site/index.html
          test -f _site/getting-started/index.html
          test -f _site/guides/index.html
          test -f _site/api/index.html
          test -f _site/troubleshooting/index.html
          echo "✅ All required documentation pages present"

      - name: Performance audit
        working-directory: docs/dev-box-site
        run: |
          # Check bundle sizes
          find _site -name "*.css" -exec wc -c {} + | awk '{sum+=$1} END {print "CSS size:", sum, "bytes"}'
          find _site -name "*.js" -exec wc -c {} + | awk '{sum+=$1} END {print "JS size:", sum, "bytes"}'

          # Verify performance budgets
          npm run test:performance-budget
