name: Security Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1" # Weekly Monday 6 AM

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install security tools
        run: |
          pip install bandit safety

      - name: Run Bandit security scan
        run: |
          # Exclude directories with vendored code, test fixtures, and build artifacts
          EXCLUDE_DIRS="./node_modules,./new-vm-test,./.git,./docs/dev-box-site/_site,./dist,./build,./.cache,./coverage,./venv,./env,./.venv,./tests,./test,**/tests/**,**/test/**"
          bandit -r . -f json -o bandit-report.json --exclude $EXCLUDE_DIRS -ll || true
          bandit -r . -f txt --exclude $EXCLUDE_DIRS -ll || true
        continue-on-error: true

      - name: Run Safety dependency scan
        run: |
          safety check --json > safety-report.json || true
          safety check || true
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
        if: always()

      - name: Security gate check
        run: |
          # Fail if high-severity issues found
          if [ -f bandit-report.json ]; then
            high_issues=$(jq '.results[] | select(.issue_severity == "HIGH")' bandit-report.json | wc -l)
            if [ "$high_issues" -gt 0 ]; then
              echo "❌ High-severity security issues found: $high_issues"
              exit 1
            fi
          fi
          echo "✅ Security gate passed"
